---
deployment:
  tasks:
    - export DYNAMIC_FORM_SYMFONY_DEPLOYPATH=/home/example/public_html/service/svc-dynamic-form-symfony
    - export DYNAMIC_FORM_SYMFONY_APP_ENV=prod
    - export DYNAMIC_FORM_SYMFONY_APP_SECRET=c0028276fe40f1bf9f0ba6e0804e96d1
    - export DYNAMIC_FORM_SYMFONY_APP_TIMEZONE=Asia/Jakarta
    - export DYNAMIC_FORM_SYMFONY_DATABASE_URL=mysql://root:@127.0.0.1:3306/dynamic_form_app?charset=utf8mb4
    - export DYNAMIC_FORM_SYMFONY_CORS_ALLOW_ORIGIN=^https?://(service.ibent95.my.id|localhost|127\.0\.0\.1)(:[0-9]+)?$

    - /bin/cp -R bin $DYNAMIC_FORM_SYMFONY_DEPLOYPATH
    - /bin/cp -R config $DYNAMIC_FORM_SYMFONY_DEPLOYPATH
    - /bin/cp -R migrations $DYNAMIC_FORM_SYMFONY_DEPLOYPATH
    - /bin/cp -R public $DYNAMIC_FORM_SYMFONY_DEPLOYPATH
    - /bin/cp -R src $DYNAMIC_FORM_SYMFONY_DEPLOYPATH
    - /bin/cp -R vendor $DYNAMIC_FORM_SYMFONY_DEPLOYPATH